variables:
- name: 'BuildTag'
  value: $[counter(format('{0}/',variables['Build.SourceBranch']), 0)]

name: $(SourceBranchName)_$(Date:yyyyMMdd).$(BuildTag)

trigger:
  paths:
    include:
    - 510-000/default.v0.form.yml
    - 510-000/default.v0.transmission.yml

steps:
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '.\510-000'
    Contents: |
      default.v0.form.yml
      default.v0.transmission.yml
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
